### ISSUE TITLE
Bulk data upload

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#220]
@lovelilyinfall asks:

> I would like to upload bulk trait data of tropical tree species to pecan. The instructions given on BETYdb for data entry mentions bulk data can be uploaded using the web interface but did not specify how. I did not find any bulk data entry options while entering new trait data to the database. Has this feature been enabled? If yes, are there more instructions listed somewhere else for bulk data entry?

* [x] question answered below
* [x] upload [feng_luquillo.csv](https://gist.github.com/dlebauer/daee0daa631f98ae73aa)
* [ ] verify that upload looks sound, and eliminate mentioned possible duplicate.

**Comment by dlebauer** [comment]
This feature exists, but is currently accessible to administrators. If you follow the instructions and use the templates in the [BETYdb data entry documentation](https://www.authorea.com/users/5574/articles/6800/_show_article), you can enter the metadata (site, treatment, citation info) into the web interface and send the upload file to an administrator (@dlebauer or @gsrohde at betydb.org or contact via the feedback tab on other instances).

As this is a new feature, feedback on how we can make the process easier and documentation more clear would be appreciated.

**Comment by lovelilyinfall** [comment]
Thanks for your help. I do not have access to the csv templates. When I clicked on "traits.csv", I get to a google drive page telling I will need permission to access the template. Can you please grant me access?

![image](https://cloud.githubusercontent.com/assets/5421381/6094861/6b4d0c3a-af0c-11e4-941f-177d3084a233.png)

**Comment by dlebauer** [comment]
@gsrohde could you please either make the templates publicly available or post them somewhere and update the link in the documentation?

**Comment by lovelilyinfall** [comment]
@dlebauer @gsrohde 

Hi David and Scott,

Can you please upload the csv file I sent to you. It is too big to be uploaded here. So I zipped it and sent to you. I have already created a citation, site and treatment in BETY.  Citation id is 782, site id is 1226 and treatment id is 2434. 

I included five variables (SLA, leafP, leafN, leafC and c2n_leaf). All of them have the units specified by BETY. However, I noticed that leafC has two units in BETY: "percent" and "g C g-1 DW". The unit of my leaf C is percent. I did not include a covariate column.

I did not enter a number for access_level. I am not sure which level to use. I am running the pecan vm and using username carya and passcode illinois. If I want to access these data with pecan vm, which access level should I use?

**Comment by dlebauer** [comment]
I haven't gotten the email ...could you try box or Dropbox (or scp to a server)?

Can you send links to the two different leafC records with different units?

Regarding access_level, if you want data exported to the VMs database, it should be public. But PEcAn will let you access BETYdb on ebi-forecast as described in the [PEcAn wiki](https://github.com/PecanProject/pecan/wiki/PEcAn-Configuration#database_access)

**Comment by lovelilyinfall** [comment]
Sorry, the email with the csv file to be uploaded was rejected due to size violation. I just got a message saying it was undeliverable. I will try something else then. 

Here is the link:
https://www.betydb.org/variables/11
https://www.betydb.org/variables/434 

Both have a variable name of "leafC", but the units are different.

**Comment by dlebauer** [comment]
I changed the name of variable 434 to leafC-mass-fraction. We will use
percent. variable 11 is the orignial and canonical value.

>

**Comment by lovelilyinfall** [comment]
Ok, thanks. For the species column, should I us USDA symbol or full species name?

**Comment by dlebauer** [comment]
The full species name

**Comment by lovelilyinfall** [comment]
Hi David, will I be able to see the data through bety web interface once it get uploaded?

**Comment by dlebauer** [comment]
yes

**Comment by gsrohde** [comment]
The data has been uploaded.

A few notes:

I specified the maximum allowable number of significant digits (4) rather than the default (3) for the measurement values.

As with all bulk uploads, all the new rows are marked unchecked.

It looks like one item in this set was entered manually through the web interface, so now we have a duplicate.  (Go to https://www.betydb.org/traits?utf8=%E2%9C%93&DataTables_Table_0_length=100&search=Psychotria&direction=asc&sort=species.genus and compare the first two rows.)

I had to add two additional species, add a date column to the CSV file, and add four additional variable names to the list of recognized trait variables before doing the upload.  See my fork of the GIST at  https://gist.github.com/gsrohde/3b0e3ad2355ab79b77aa .

**Comment by lovelilyinfall** [comment]
Thanks! I did enter a SLA value for Psychotria berteriana to test if I can enter traits manually. But I do not see a duplicate at the given link. This is a screen shot of what I see. I would like to delete the duplicate? Has it been deleted?
![capture](https://cloud.githubusercontent.com/assets/5421381/6140185/c7db8302-b162-11e4-8575-24c641fe9491.JPG)

**Comment by dlebauer** [comment]
I deleted i

**Comment by lovelilyinfall** [comment]
Also, for future reference, I want to make the csv file better to make it easier for you to upload. I understand that the csv file should have a date column, but the template does not specify what format the date should be in, yyyy-mm-dd, or mm-dd-yyyy? In addition, if I want to include a covariate for a variable, how do I let you know in the csv the covariate is not a second variable?

**Comment by dlebauer** [comment]
Covariates: there is a list in the documentation of required covariates - things like leaf temperature. I think it is in the appendix. (@gsrohde, has this been updated?) 

But all records in a row are linked by a common `entity_id`, so, eg your leafN and leafC could be queried. 

You might need to update the PEcAn query.traits function to use this, in particular to avoid using both leafN and c2n_leaf in an analysis (note that the function uses a fixed value of leafC)

**Comment by lovelilyinfall** [comment]
so if i have leaf N and c2n_leaf, the PEcAn query. traits function will get two c2n_leaf values for me?

**Comment by dlebauer** [comment]
I think it will assign a mean, n=2, and a SE. This should be a bug on the
pecan repository.

**Comment by gsrohde** [comment]
Regarding the recognized trait variables and covariates list, it can be viewed here: https://www.betydb.org/trait_covariate_associations

Currently, for a column heading to be recognized as the name of a trait variable or covariate, it must be in this list.  And for a trait variable to be in this list, it must have at least an optional covariate.  So when adding the 4 new trait variable names to the list for this upload, I somewhat arbitrarily gave them an optional covariate of canopy_layer.  (I say "somewhat" arbitrarily, but I choose this covariate since all of the previously-listed trait variables had canopy_layer as an optional covariate.)

If it makes sense to allow adding trait variable names to the list without having to associate them with any covariate, this might be easy to change.  Less easy (I think) would be to allow certain variable names to be recognized as trait variables in some contexts and as covariates in other contexts.  (I say "I think" because I'm not sure how things would work now if the table happened to have a variable name that occurred in both columns.)  For example, currently, leafT is recognized as a covariate name, but leafC, leafP, and leafN are recognized as trait variable names.

**Comment by dlebauer** [comment]
@gsrohde this is sensible: T is temperature; C, N, P are elements.
