### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#225]
- [This version of a csv](https://www.dropbox.com/s/vas28bbg8msquwu/feng_luquillo_invalid_byte_sequence.csv?dl=0)  prepared by Xiaohui for bulk upload (gh-220) produces an "Invalid byte sequence error".
- [This version of the file](https://www.dropbox.com/s/494x4cmdduj9hju/feng_luquillo_fixed.csv?dl=0), which I copy-pasted to a gist and then downloaded as 'raw' does not

(note that these files still have a few issues, but this issue is not related to the byte sequence error dealt with here).

from pecandev:/usr/local/ebi/log/production.log

``` ruby
Started POST "/bety/bulk_upload/display_csv_file" for 128.174.125.237 at 2015-02-10 11:17:14 -0600
  Processing by BulkUploadController#display_csv_file as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+o9U4CzQbDxJILEFlsq7IiM7jsmRblQ9yHbqDePYc8Q=", "commit"=>"Upload and validate file >>", "CSV file"=>#<ActionDispatch::Http::UploadedFile:0x00000018723e00 @original_filename="BETYtraits (1).csv", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"CSV file\"; filename=\"BETYtraits (1).csv\"\r\nContent-Type: application/vnd.ms-excel\r\n", @tempfile=#<File:/tmp/RackMultipart20150210-7834-1we6fdd>>, "new upload"=>"{:value=>true}"}
Redirected to http://pecandev.igb.illinois.edu/bety/bulk_upload/start_upload
Completed 302 Found in 53ms


Started GET "/bety/bulk_upload/start_upload" for 128.174.125.237 at 2015-02-10 11:17:14 -0600
  Processing by BulkUploadController#start_upload as HTML
Rendered feedback/_fbtab.html.erb (224.7ms)
Rendered bulk_upload/start_upload.html.erb within layouts/application (251.4ms)
Completed 200 OK in 256ms (Views: 252.9ms | ActiveRecord: 2.0ms)
```

**Comment by gsrohde** [comment]
@dlebauer  It's not clear what more needs to be done here; the data has been uploaded with the corrected file.

It's probably true the error message could be more helpful, such as telling where in the file there error occurs.  At the very least, the documentation should be clear about the requirement that the file be valid UTF8.  If this is something you want me to address, add a comment here to that effect or make a new issue for it.

**Comment by dlebauer** [comment]
Adding instructions to export from Excel as UTF-8 to the documentation would just make it even more dense, and this should be something we can automate. 

The gem [Charlock Holmes](https://rubygems.org/gems/charlock_holmes) seems to provide a more comprehensive solution. Or maybe this won't be an issue in later versions of rails (seems v 1.9.2 is oft-cited)

But maybe this solution on [Stackoverflow](http://stackoverflow.com/a/4697471/199217), or one of the variants posted there or on [this related question](http://stackoverflow.com/q/5053216/199217) will provide a simpler solution. I think it will be reasonable to assume that exporting from Excel will be the most common source of this error.


```ruby
File.open(file, "r:windows-1251:utf-8").each_line { |line| puts line.strip(",") }
```

**Comment by dlebauer** [comment]
If we can do a one or few liner (e.g. from above), please implement this so that it can handle csv files exported from Excel more cleanly.

**Comment by gsrohde** [comment]
What I could do is this: 

If the file fails to parse as UTF-8, then I could retry with ISO-8859-1 (= Latin1)--or rather, WINDOWS-1252, which is a superset of ISO-8859-1, perhaps issuing a warning.  (The warning could also specify the line number of the first line that won't parse as UTF-8.)  Since every file will parse as WINDOWS-1252  (I think), I can't really try to guess other possible encodings (e.g., ISO-8859-5 (Cyrillic), ISO-8859-7 (Greek)) without more sophisticated logic.  

(A potential danger is that perhaps someone starts with a UTF8-encoded CSV file, then maybe somehow pastes in one string in WINDOWS-1252, making the file unparsable as UTF-8.  Then on attempting an upload, it is reparsed as WINDOWS-1252 yielding a bunch of weird looking character strings.)

While I wouldn't call this a one-liner (probably at best it's a few plus a few more-liner), it would not be too odious to implement.  I'm curious, though, why most of the EXCEL files I've gotten seem fine but this one had a problem.  Was it the way it was exported, or some settings in place when the file was created, or the way it was created, or the version of EXCEL used?  Perhaps it was created outside of EXCEL and then imported.

**Comment by cupofjoakim** [comment]
Any chance the invalid test file would be uploaded again?

**Comment by dlebauer** [comment]
@cupofjoakim thanks for your interest - I've updated the files with the new links, and for the record have also attached them here: 
[bety_github.zip](https://github.com/PecanProject/bety/files/1514309/bety_github.zip)

**Comment by dlebauer** [comment]
@cupofjoakim I'm curious what brought you this issue and if you have any thoughts or interest in submitting a fix?

**Comment by cupofjoakim** [comment]
@dlebauer I was thinking of looking at it. We had a similar issue at work the other day, but ultimately decided not to support any other format than UTF-8. The issue always seems to be excel and whilst we found a couple of semi-shitty workarounds (like this one: https://stackoverflow.com/a/25647019) we didn't feel comfortable with any of them and decided to throw an error for the user instead.

**Comment by dlebauer** [comment]
@gsrohde I am going to close this ... an informative error would be nice but in the scope of work we have a low priority.
