### ISSUE TITLE
Upload revised Miscanthus dataset 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#254]
TODO
* [ ] upload mischanthus data
* [ ] merge with previously existing records 

@echeng7 reviewed Miscanthus records (per [Redmine 2271](https://ebi-forecast.igb.illinois.edu/redmine/issues/2271)). 

The data are in this [google spreadsheet](https://docs.google.com/spreadsheets/d/1hrvMTMc7scvQFgit7QqF68vfxxNufNC--3RJfSDhne4/edit#gid=1587131847)
* download the [miscanthus sheet as csv here](https://docs.google.com/spreadsheets/d/1hrvMTMc7scvQFgit7QqF68vfxxNufNC--3RJfSDhne4/export?format=csv&gid=1587131847).

These are ready to update. Where records have ids, the data in the spreadsheet should replace existing data. 

* Turn off foreign key constraints. We will break many, and then have to fix them again.
* could give all a new id and delete old records, then update id field with original id 

For now
* ignore columns fertilizer_n, planting_density, planting_date, rotation, season, irrigated
 * these should be in managements (I think Emily already put them there)
* ignore lat, lon, mat, country (these should be associated via sites)

Report any issues / or required corrections to data here

**Comment by gsrohde** [comment]
I was partly wrong about the citation column headings: Not "citations.author", but not "author" either--it's "citation_author", etc.

Other corrections: "sitename" --> "site", "cultivars.name" --> "cultivar".

These are easy corrections which I could do.

Somewhat more problematic are:

"date" values must give year, month, and day:  "1999" is not a valid entry, but "1999-01-01" is.

Missing values should be represented by the empty string, not "NA".  (This would be an easy search-and-replace on a text version of the file; for example, replacing ",NA," with ",," should work with this particular file.

I've run into a bug with the bulk upload that I have to fix.  I think it has to do with the size of this data set.  I might be able to work around it by doing the upload in batches, but I'd like to see first if it's an easy fix.

**Comment by gsrohde** [comment]
By "citation_author", etc." I meant the year and title also need to be changed (to citation_year and citation_title).

We don't currently do anything with dateloc.  Maybe we should.  At one point, I think we talked about allowing YYYY and YYYY-MM in addition to YYYY-MM-DD and then setting dateloc automatically accordingly, but we dropped or tabled the idea.

I found that going back to using the sessions database table for storing session data seemed to fix the bug I ran into, but I want to do a little more research before I make the switch.

**Comment by dlebauer** [comment]
This dataset is a 'special case'. As long as you record the final yields.id
value for each row in the spreadsheet, we can update dateloc using SQL.

**Comment by gsrohde** [comment]
COMMENT IN PROGRESS


Column value errors:

In general, the treatment column value should match the "name" column of the treatments table.  Often (or maybe always when a definition exists) the definition has been appended to the column value (usually or always separated from the name by a colon).

Errors by citation:

Acaroglu: Treatment name is "Control" not "Control : Observational".

Bullard: Treatment name is just "Low Density" or "High Density".

Danalatos 1996: There are two treatments for this citation, both named "Observational".  One is the control and the other has "No Irrigation" in the definition.  Unfortunately, the uniqueness-by-citation constraint on treatment names is not yet enforced, and the bulk-upload code can't handle duplicate names.  Perhaps the best solution is to rename the second treatment, say to "Observational-NI".

Danalatos 1998: Just the treatment name, not the definition should appear.  Everything from the space before the colon to the end of the string should be removed.

Himken: Again, "Control", not "Control : Observational"

Kilpatrick: Again, everything from the space before the colon to the end of the string should be removed.  "March Planting", "Apr Planting", etc. is not part of the treatment name.

Lewandowsky 1997: This is another case where treatment names are not unique per citation.

**Comment by echeng7** [comment]
I have updated all the treatments. 

I'm not sure if you still want me to anything with the dates / dateloc.

**Comment by dlebauer** [comment]
@echeng7 don't worry about dateloc - these will be inserted programatically (as mentioned in my previous comment)

**Comment by gsrohde** [comment]
@echeng7 Where is the updated spreadsheet?  The "google spreadsheet" link above just downloads a short file called "all.yielddata - Color Codes.csv" with no data in it.

**Comment by echeng7** [comment]
There should be data on the sheet tabs at the bottom.

**Comment by dlebauer** [comment]
@gsrohde The link I posted directs to csv. Try removing format=csv or look
in your google drive

**Comment by gsrohde** [comment]
@dlebauer The link _does_ get a csv file--unfortunately, it downloads the wrong sheet of the Excel file.

I went directly to my google drive and found what I wanted.

**Comment by gsrohde** [comment]
@echeng7 Ok, now all treatment names match what's in the database except one:

"propagation method, unfertilized : micropropagation by in vitro tillering" doesn't match any treatment associated with Lewandowski 1997.

There are other problems.

@echeng7 I don't know why you changed the species column entries since I didn't mention these being a problem, but please change them back to what they were!  The species column should contain the full binomial species name!  ( @dlebauer Is this too confusing to have this mean something different than the the species column in the species database table?  I didn't foresee this being a problem since I figured the layout of the database tables would be under the hood for most users.  But perhaps we should call the column `full_species_name` instead of just `species`.  It's a little extra typing but might save a lot of confusion.)

@dlebauer There are multiple rows with sitename "ADAS Arthur Rickwood".  Similarly for "Boitzenhagen".  Did we agree to deal with these for now by appending "-duplicate" to one of the entries?  (Also, I had to correct some site names: "ADAS Rickwood" --> "ADAS Arthur Rickwood" in rows 441--442; "ADAS High Mowthrope" --> "ADAS High Mowthorpe" in rows 543--549; "Ascherberg" --> "Ascheberg" in rows 635--638.  

@dlebauer There is one more sticky problem with site names: There is both a site called "Gutenzell" and one called "Gutenzell-Hürbel".  Both are associated with citation Lewandowski 1998, but only "Gutenzell-Hürbel" is associated with Lewandowski 1997.  So presumably the site name in rows 454--457 should be "Gutenzell-Hürbel" rather than "Gutenzell".  If so, I will probably have to change this (or change it again) after download since Excel doesn't seem to convert non-ASCII characters correctly when saving as CSV.  [UPDATE: I just noticed that in the previous version of the CSV file, the sitename "Bayerische Landesanstalt für Weinbau und Gartenbau (LWG)" was encoded in UTF-8 correctly when I downloaded it, but after I edited the spreadsheet and downloaded it again, it wasn't.  Perhaps I did something differently when I downloaded and saved it or perhaps there's some problem with the way Excel works on a Mac.]

@dlebauer Rows 318 and 330 are still missing yield values.

@dlebauer The cultivars in rows 530--577 aren't in the database.  Here's a query showing all cultivars with 'EMI' in the name, along with their species names:

```sql
ebi_production=# select s.id,scientificname, c.name from species s join cultivars c on c.specie_id=s.id where c.name ~ 'EMI';
  id  |       scientificname       |  name  
------+----------------------------+--------
 1477 | Miscanthus x giganteus     | EMI-01
 1477 | Miscanthus x giganteus     | EMI-02
 1477 | Miscanthus x giganteus     | EMI-03
 1477 | Miscanthus x giganteus     | EMI-04
 1479 | Miscanthus sinensis Hybrid | EMI-06
 1479 | Miscanthus sinensis Hybrid | EMI-07
 1479 | Miscanthus sinensis Hybrid | EMI-08
 1479 | Miscanthus sinensis Hybrid | EMI-09
 1479 | Miscanthus sinensis Hybrid | EMI-10
 1478 | Miscanthus sinensis        | EMI-11
 1478 | Miscanthus sinensis        | EMI-12
 1478 | Miscanthus sinensis        | EMI-13
 1478 | Miscanthus sinensis        | EMI-14
 1478 | Miscanthus sinensis        | EMI-15
 2157 | Miscanthus sacchariflorus  | EMI-05
(15 rows)
```
The species of interest, Miscanthus sacchariflorus, has only cultivar EMI-05.  We need cultivars EMI-06 to EMI-53.


@echeng7 If there is no data in a cell, it should be entirely blank.  Right now there are pairs of double quote marks instead.  @dlebauer Is this an artifact of the way google sheets does things?  I can easily remove the quotes after download, but it would be nice if I didn't have to.

**Comment by echeng7** [comment]
@gsrohde I have fixed the one treatment that was incorrect. 

Also, I assumed that I made a mistake with the species because for the cultivar I had listed genus, species, and cultivar instead of only cultivar. They have been corrected now.

**Comment by gsrohde** [comment]
@dlebauer The spreadsheet looks good now except for the four items which I put checkboxes for in my most recent comment.  Please fix or instruct Emily as to what you want done.

(Also, I'm still having to delete double quote marks from empty fields after I download the spreadsheet, but it isn't much trouble to delete them.)

**Comment by dlebauer** [comment]
@echeng7 can you please address the issues with checkboxes, and mark the boxes done when fixed?

**Comment by echeng7** [comment]
@gsrohde I believe all issues have been addressed. However, I am unable to mark the boxes.

**Comment by echeng7** [comment]
@gsrohde  After reviewing with Dr. LeBauer, Rows 318 and 330 (Yields 958 & 970) were deleted off the GoogleDoc as it was a summation yield over the entire experiment.

**Comment by gsrohde** [comment]
@echeng7 and/or @dlebauer : The only thing remaining to be resolved is the Gutenzell vs. Gutenzell-Hürbel problem.  I see you marked the one called Gutenzell as a duplicate, but I'm not sure it is: The two sites have different mat, map, and soil types, and, going by either the geometry (lat,lon) or the city names, the two places are an hour and a half apart by car.  In any case, marking the Gutenzell one as a duplicate doesn't help with the upload: The CSV file refers to a site with name "Gutenzell" and now there isn't one.  There either has to be a site called "Gutenzell" that is associated with citation Lewandowski 1997, or we have to assume that the CSV file should have said "Gutenzell-Hürbel" in rows 452--455 and change it to do so.

**Comment by dlebauer** [comment]
@echeng7 could you please check the original references? Seeing as all
citations associated with these sites are from Lewandowsky, it is likely
that these are nearby. The differences in MAT/MAP could be due to the
source of this data;

However, the differences in soil may indicate that these experiments were
conducted in different fields or plots. It would be worth checking. If
these really are all the same sites, great. But if they are distinct, we
should try to keep the experiments associated with the appropriate field /
plot / soils

@gsrohde sometimes lat/lon isn't always provided, so it is possible the
person who created one or both sites had to 'guess' the lat/lon and climate
based geographic names

**Comment by echeng7** [comment]
@gsrohde @dlebauer 
All the Lewandowski citations state "Gutenzell," however, if you type in the lat/lon into GoogleMaps, it says Gutenzell-Hürbel. 

Additionally, I made a chart on each of the citations Lewandowski is associated with. There are some differences in the elevations, mean annual precipitation, and types of soil/texture. 
![image](https://cloud.githubusercontent.com/assets/3441501/6420340/e3ef373e-be8a-11e4-819d-fcfafe5d718a.png)

Where should I go from here?

**Comment by dlebauer** [comment]
SDo, only one has latitude and longitude? Can you check the original
citations - can you tell if these are the same site, perhaps different
plots within the same site?

If they are different plots at the same site, can you identify the
different names used in the original publication to distinguish the
different fields. Even a sitename like "Miscanthus Field Planted in 1999"
I suspect the differences in elevation are due to, e.g. someone using
google earth to look them up.

**Comment by echeng7** [comment]
The information above was all I could extract from the original citations. Since it was all written by the same author, I would assume that it is the same site and different plots. However, based on Google maps, Gutenzell-Hurbel is a pretty large city so all the info is not specific enough.

**Comment by dlebauer** [comment]
When in doubt, ask Iris_Lewandowski@uni-hohenheim.de

**Comment by gsrohde** [comment]
@dlebauer

I uploaded all rows not involving site "Gutenzell".  The resulting rows have ids 17651--18295.  I did a sort of sanity-check query under the assumption that the rows with the id numbers listed in the yields.id column of the spreadsheet should match the newly-inserted rows and that the order corresponds as well.  The query had the form
```sql
SELECT
    y1.id || ' vs. '||y2.id AS ids, 
    y1.citation_id || ' vs. ' || y2.citation_id as citation_ids, 
    y1.site_id || ' vs. ' || y2.site_id as site_ids, 
    [ETC.]
FROM
    yields y1,
    yields y2
WHERE
(
     y1.citation_id != y2.citation_id OR
     y1.site_id != y2.site_id OR
     [ETC.]
)
AND
(
     y1.id =971 AND y2.id = 17651 OR 
     y1.id =972 AND y2.id = 17652 OR 
     y1.id =973 AND y2.id = 17653 OR 
     [ETC.]
);
```

In other words, it joins the yields rows that should correspond, pair by pair, and displays the pairs of discrepant values when there is a discrepancy.

I found no discrepancies between citation_id, site_id,  or treatment_id values.  There were only five cases where the value in the mean column differed, and in all but one of these cases there was not a difference if both values were rounded to 3 s.d.  (The remaining case--11.68 vs. 11.86--may be a clerical error.)

When both cultivar_id values were non-null, they always matched, but in 41 cases, one was NULL and the other was not.

On the other hand, there were 18 rows where the specie_id values differed.  A third of these had 2157 (Miscanthus sacchariflorus) as the old id and 1477 (Miscanthus x giganteus) as the new one; the rest were the other way around.

As for the method_id column values, the new rows always had this set to NULL.  The old rows always had either 3 or NULL.

The biggest discrepancy was in the date column values: 275 pairs had non-matching dates and in 59 of those cases even the year did not match.

A brief run down on the remaining columns:

* dateloc: Because of a bug in the bulk upload code, the values from the CSV file were actually used.  (If this is desired behavior, then it is a bug that the wizard says that column will be ignored.) 235 pairs had differing values here (not surprising given the date discrepancies).
* statname, stat, n, and notes: Since these columns are not in the CSV file, they are always NULL in the new rows.  But some of the old rows have values for these.
* access_level: This is always 4 (public) for the new rows.  The old rows have either 4 or 1.
* checked: This is always 0 for the new rows and 1, 0, or NULL for the old rows.
* created_at, updated_at, user_id: These are obviously different for the new rows.


I have a script ready to go which would delete each old row and update the id of a new row to take its place.  It has the form
```sql
DELETE FROM yields WHERE id = 971;	UPDATE yields SET id = 971 WHERE id = 17651;
DELETE FROM yields WHERE id = 972;	UPDATE yields SET id = 972 WHERE id = 17652;
DELETE FROM yields WHERE id = 973;	UPDATE yields SET id = 973 WHERE id = 17653;
DELETE FROM yields WHERE id = 974;	UPDATE yields SET id = 974 WHERE id = 17654;
DELETE FROM yields WHERE id = 975;	UPDATE yields SET id = 975 WHERE id = 17655;
...
[ETC.]
```

Alternatively, if you want to replace the old rows but aren't quite ready to delete them completely, you could invert their id numbers so that the old row 971 (for example) becomes row -971:
```sql
UPDATE yields SET id = -971 WHERE id = 971;	UPDATE yields SET id = 971 WHERE id = 17651;
...
[ETC.]
```

Also, perhaps the script should copy some of the information from the old rows (e.g., stats, notes).

**Comment by dlebauer** [comment]
The fact that there are differences between the old records and the new is
expected - this was the objective.

I'd rather keep the old records in a different database than having
negative ids. Actually, if you could post both as gists, I'd like to take a
look.

I think we should keep any of the rows (n, stat, notes) that Emily did not
check. Does that sound correct @echeng7?

**Comment by echeng7** [comment]
Yes please keep those rows. Thanks.

On Thu, Mar 5, 2015 at 9:12 PM, David LeBauer <notifications@github.com>
wrote:

> The fact that there are differences between the old records and the new is
> expected - this was the objective.
>
> I'd rather keep the old records in a different database than having
> negative ids. Actually, if you could post both as gists, I'd like to take a
> look.
>
> I think we should keep any of the rows (n, stat, notes) that Emily did not
> check. Does that sound correct @echeng7?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PecanProject/bety/issues/254#issuecomment-77499559>.
>



-- 
Emily Cheng
University of Illinois at Urbana-Champaign | 2015
Molecular and Cellular Biology Major | Chemistry Minor
Pre-Student Osteopathic Medicine Association | UIUC Chapter President
Illini Emergency Medical Services | Records Officer | EMT- B

**Comment by echeng7** [comment]
I have received an email back from Ms. Lewandowski and she has confirmed that the location is Gutenzell-Hürbel. She states that she does not have the coordinates but the data was extracted from the same field. How should I go about editing the sites since they have different soils and elevations? 
@dlebauer @gsrohde

**Comment by dlebauer** [comment]
@echeng7 can you ask her why there are different soil types reported? Are
these different plots within the same field, or the same exact field?

**Comment by gsrohde** [comment]
@echeng7 I just noticed there are two rows with yields.id = 16942.  They are the same except for the date: one is 1995 and 1994.  Could you double-check these?

**Comment by echeng7** [comment]
@gsrohde I have changed the sheet to reflect the edit.

On Mon, Mar 9, 2015 at 11:29 AM, gsrohde <notifications@github.com> wrote:

> @echeng7 <https://github.com/echeng7> I just noticed there are two rows
> with yields.id = 16942. They are the same except for the date: one is
> 1995 and 1994. Could you double-check these?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PecanProject/bety/issues/254#issuecomment-77888878>.
>



-- 
Emily Cheng
University of Illinois at Urbana-Champaign | 2015
Molecular and Cellular Biology Major | Chemistry Minor
Pre-Student Osteopathic Medicine Association | UIUC Chapter President
Illini Emergency Medical Services | Records Officer | EMT- B

**Comment by gsrohde** [comment]
@dlebauer Here is a GIST containing three SQL statements: https://gist.github.com/gsrohde/b4b4e12878364b05f5c6

The first saves the information from the old miscanthus rows (listed by id in the yields.id column of the CSV file) to a file in CSV format.

The second copies information from the newly-added rows (from the upload) to the old rows.  This is what you should look over most carefully, to make sure we copy what we want to be updated and only what we updated.  (Note, among other things, that I don't copy the "created_at" value even though some of the old rows have NULL here.)

The third deletes the rows created by the upload now that we are done copying information from them.

**Comment by dlebauer** [comment]
@gsrohde that looks good please go ahead with the upload.

The only question is the comment that y2.user_id is the last person to edit the row - it makes sense that it is handled this way, but is this the default in the rails application?

**Comment by gsrohde** [comment]
@dlebauer I already did the upload (except for the Gutenzell rows).  Did you mean go ahead and run the scripts in the Gist to save the old rows; update them with data from the new rows; and delete the new rows?

Regarding the SQL statements in the GIST: I think you were right about how `user_id` is used.  We use it to signify the person who created the row.  (In fact, the Rails app displays this as "Record creator".)  So I changed the GIST to not update the `user_id` values in the old rows _except_ in the case where there is no value (i.e., NULL is stored) in which case I do update it (figuring some information is better than none even though I'm not _really_ the record creator).  One other thing: Perhaps I should update the value of `mean` as well.  There is only one case where the old and new values differ significantly:

```sql
ids					means
16954 vs. 18236	11.6800 vs. 11.8600
974 vs. 17654	1.5100 vs. 1.5080
972 vs. 17652	1.5700 vs. 1.5730
971 vs. 17651	1.5000 vs. 1.4950
973 vs. 17653	1.6400 vs. 1.6440
```

In the other four cases the difference is only a matter of how much they were rounded.  Probably I'll just keep the GIST code as it is and update that one value manually.  Or shall I query Emily to make sure the new value is the correct one?


Once I run the GIST code, the only remaining thing to do for this set (I think) is to upload the Gutenzell rows.  It seems that Emily still hasn't responded to your request from March 9th to have her query Ms.  Lewandowski about the different soil types.

**Comment by dlebauer** [comment]
* @gsrohde Per the lead researcher for these studies, all of the Gungtzell rows are identical and should use the site "Gutenzell"
* go ahead and run the gist code, assuming the newer value is correct 
 *  @echeng7 please confirm that the new value is correct, or else fix the record after Scott has run the updates

**Comment by gsrohde** [comment]
@echeng7 Emily, I was wondering why so many rows where the date column had year and month information or full year, month, and day information before now only have a year?  I'd say a dozen or two at least.  For example, the rows with yields.id values 892--911.  For example, the row with id 892 currently has date value 1993-04-10 in the database, but your spreadsheet just has original_date value 1993 (which goes into the database as 1993-01-01).

**Comment by gsrohde** [comment]
@dlebauer It's still not clear which of the two Gutenzell sites I should use (275 or 276), or should I just pick one?

**Comment by dlebauer** [comment]
* it is clear that the date should be kept if the spreadsheet gives year and the database has yyyymmdd, assuming the year value is the same
* use the site that is not marked duplicate

**Comment by gsrohde** [comment]
I've updated the old rows from the newly-uploaded ones and then deleted the latter.

@echeng7 Could you double-check the yield value (the mean) for https://www.betydb.org/yields/16954?  It was 11.68 and is now 11.86.  I want to make sure this wasn't just a typo.

I still have to upload the Gutenzell-related yields.

**Comment by gsrohde** [comment]
Gutenzell yields have now been uploaded.  This can be closed pending Emily's response to the immediately preceding comment.

**Comment by echeng7** [comment]
It is supposed to be 11.86. It was entered incorrectly the first time.

On Thu, Apr 9, 2015 at 3:19 PM, Scott Rohde <notifications@github.com>
wrote:

> Gutenzell yields have now been uploaded. This can be closed pending
> Emily's response to the immediately preceding comment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PecanProject/bety/issues/254#issuecomment-91346222>.
>



-- 
Emily Cheng
University of Illinois at Urbana-Champaign | 2015
Molecular and Cellular Biology Major | Chemistry Minor
Pre-Student Osteopathic Medicine Association | UIUC Chapter President
Illini Emergency Medical Services | Records Officer | EMT- B
