### ISSUE TITLE
Correct config for pg_hba.conf

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#259]
In the RHEL documentation for PostgreSQL it is listed that the correct config for the pg_hba.conf file is:

In this file, you will see a line like this local all all peer Assuming this is a fresh install of PostgreSQL, you can give password access to user bety by adding the line local bety bety md5 immediately before this. Then save the file.

However I have also been told:

Fix postgresql
add this to the top of /usr/pgsql-9.3/data/pg_hba.conf
local   all             bety                                    trust
host    all             bety            127.0.0.1/32            trust
host    all             bety            ::1/128                 trust

Which is the correct setup?

**Comment by robkooper** [comment]
I think they are equivalent, the first bety indicates only access to database bety not others (like FIA). the MD5 indicates what password to use.

the 127.0.0.1 and ::1/128 is just alos allow this coming from a network connection and not just a socket. This is needed otherwise PEcAn code might not work since it tries to connect to localhost.

**Comment by serbinsh** [comment]
Got it.  I think I will leave it setup with the multiple entries.

**Comment by gsrohde** [comment]
FYI

The two general formats for configuring client authentication used here are
```
local      database  user  auth-method  [auth-options]
host       database  user  address  auth-method  [auth-options]
```
So besides the difference between using "all" and "bety" in the database slot that Rob mentioned, there's the difference between using "trust" and "md5" as the authentication method.  "trust" means anyone who has access to the server can log in to the database as the specified user (in this case "bety") without needing a password.  "md5" means they need to use the password to  log in.  If you don't need the extra layer of security, then "trust" is fine.

(Also, the last line (with address ::1/128) is redundant, since even IPv6 connections will recognize IPv4-style IP addresses (127.0.0.1/32).  But it doesn't hurt anything either.)
