### ISSUE TITLE
Upload Switchgrass Data Set

### ISSUE THREAD

**Issue by echeng7** [PecanProject/bety#263]
Data are in the [all.yielddata](https://docs.google.com/spreadsheets/d/1hrvMTMc7scvQFgit7QqF68vfxxNufNC--3RJfSDhne4/edit#gid=1987818390) Google doc spreadsheet here:

**Comment by echeng7** [comment]
@dlebauer @gsrohde

**Comment by gsrohde** [comment]
I assumed the spreadsheet to use is the switchgrass tab of the all.yielddata Google doc spreadsheet here: https://docs.google.com/spreadsheets/d/1hrvMTMc7scvQFgit7QqF68vfxxNufNC--3RJfSDhne4/edit#gid=1987818390

@echeng7 Is there any reason you didn't just delete the greyed-out lines that are to be ignored?  Are they there for a reason?

Here is a summary of problems:

1. The Balasko paper "Yield and Quality of Switchgrass Grown without Soil Amendments" has a publication date of 1984, not 1982.
2. The "Northern Great Plains Research Laboratory : Mandan X" sites where X > 2 don't yet exist.
3. There is no site with sitename "Chickasha, Oklahoma".
4. On the other hand, there are two sites with sitename "Chickasha, OK".  They have different values in their soilnotes and map columns and slightly lat,lon values, and significantly different elevations.
5. There is no Panicum virgatum cultivar with name MT279.  There is one with name PMT279, however.
6. There is no site with sitename "Haskell, Oklahoma".  There is one with name "Haskell, OK", however.
7. There is no site with sitename "Mead, Nebraska".  There are several sites, however, with city "Mead" and state "NE" or "Nebraska".
8. There is no site with sitename "Ames, IA".   There is a site, however, with city "Ames" and state "IA".
9. There is no site with sitename "West Lafayette, IN".  There is one site, however, with city "West Lafayette" and state "IN".
10. There are two sites with sitename "E.V. Smith Research Center" (and a third with sitename "E. V. Smith Research Center", that is, with a space between the "E." and the "V.").  They all differ slightly.
11. The data set has references to both "Missaoui	   2005	The effect of low plant density on response to selection for biomass production in switchgrass" and "Missaoui	   2005	The effect of low plant density on response to selection for biomass production in switchgrass-duplicate".  Is there any reason not to choose one or the other?
12. There are three sites with sitename "University of Georgia Plant Sciences Farm".
13. There is not cultivar with name "Kanlow L619".
14. There are two sites with sitename "University of Bologna".
15. The site "Beeville, TX" isn't a site associate with citation "Muir	2001".  There is, however, a site that is having no sitename but city "Beeville" and state "TX".
16. There is no Panicum virginatum cultivar with name "NCSU-2".  There is one, however, with name "NCSU2".  Similarly for "NCSU-1".
17. Cultivars "PMT-279" and "PMT-785" are in the database as "PMT279" and "PMT785", respectively.
18. There is no site with sitename "College station, TX".  There is one with sitename "College Station".
19. There is no site with sitename "Dallas, TX".  There is one with sitename "Dallas" and it's in the state of Texas.
20. There is no Panicum virginatum cultivar with name "Kansas Native".  There is one with name "Kansas".
21. The `date` column is always blank.  Presumably, since the `original_date` column is always just a year, this column should equal the `original_date` column value with "-01-01" appended.

**Comment by dlebauer** [comment]
@echeng7 can you review and fix each of these issues?

**Comment by gsrohde** [comment]
@echeng7 I'm in the process of making a few notes on how to fix some of these issues.

**Comment by echeng7** [comment]
Will do. I've had several exams yesterday and today and I will be at a
conference this weekend but I will work on them as soon as I can.

**Comment by gsrohde** [comment]
@echeng7 I'm finished making notes.  If the problems for two items were basically the same, I didn't necessarily make a note for each one.  Let us know if you have any questions about how to fix these.

If you want to learn how to use the bulk-upload validator yourself, stop in next time you are in the neighborhood and we can show you.

**Comment by echeng7** [comment]
- Is there any reason you didn't just delete the greyed-out lines that are to be ignored? Are they there for a reason?
I left them there because they were on the original site but I am unable to check them due to various reasons. I would like to go back to them if I am able to get access to them. 

- As you have said, "there are two sites with sitename "Chickasha, OK". They have different values in their soilnotes and map columns and slightly lat,lon values, and significantly different elevations. Append "-duplicate" to the sitename of one of them." 
How should I determine which should be duplicated? 

- Missaoui 2005 The effect of low plant density on response to selection for biomass production in switchgrass : Information was previously entered under a different citation but was supposed to be in the Missaoui 2005 citation. The easiest way to "combine" them for now, as Dr. LeBauer told me, was to make a duplicate citation. 

- University of Bologna 
3: Lat. 44°25′, Long. 11°28′,80 m a.s.l
354: 44°33′N, 11°21′E, 32 m a.s.l.
Should I combine them? 

- The date column is always blank. Presumably, since the original_date column is always just a year, this column should equal the original_date column value with "-01-01" appended.
I will not be changing the dates as they have been checked manually through the database. 

Everything else should be updated. I will come in sometime this week to learn!

**Comment by gsrohde** [comment]
@echeng7 Some answers (and a question) ...

* Chickasha, OK - "How should I determine which should be duplicated?": It's arbitrary, though if you can easily tell that one site is referred to by traits or yields more often than the other, then mark the less-used site as the duplicate.  
Eventually, we want to eliminate duplicate site names (or, if the sites really do have some significant difference, do a renaming to give them meaningful but distinct site names).  But for now, whenever you run across duplicate column values for site.sitename, species.scientificname, or citation author-year-title combinations, just append "-duplicate" to all but one of them.

* "University of Bologna": Again, append "-duplicate" to the sitename of one of these.

* date column: If you don't need to upload any date data, then just leave out this column.  Alternatively, if for some reason you don't want to delete the column, rename it to "date-ignore".

I'm not quite sure what you were saying about the Missaoui citation.  My point was, although I understand why one is marked "-duplicate" in the database, why not always have your dataset file refer to the one not marked "-duplicate"?

**Comment by echeng7** [comment]
For the Missaoui citation, the dataset does refer to the one not marked duplicate. However, in this case, the yields in both citations that were entered in need  to in the system. Those from the duplicate citation should be later associated with the one not marked with duplicate. Does this make more sense? @gsrohde

**Comment by gsrohde** [comment]
@echeng7 Some of the rows are greyed out in some columns but not in others.  It's unclear to me if these rows should be included in the upload or not.  The rows in question are:
* rows 279-281: Columns G and H are greyed out.
* rows 347-522 (the "Fike" citation rows): All columns are greyed out except for A, B, D, and G.
* rows 1182-1229 and 1319-1366: These are greyed out in column A.  Is this significant?
* rows 1751-1770: These are greyed out in columns G and H.

(Some of the grays are darker than others.)

If the greyed-out rows represent rows that aren't ready for upload but that you may want to go back to later, the best procedure would to move these rows to a different data sheet.  (You could call it "Switchgrass data part 2" or something like that.)  Please only hand off to me as "ready to upload" data sheets where all the rows are to be uploaded.  This way I don't have to manually remove rows before doing an upload, and I don't have to guess which rows really are supposed to be removed.

**Comment by echeng7** [comment]
The switchgrass tab should be ready for upload now.

On Mon, May 4, 2015 at 11:29 AM, Scott Rohde <notifications@github.com>
wrote:

> @echeng7 <https://github.com/echeng7> Some of the rows are greyed out in
> some columns but not in others. It's unclear to me if these rows should be
> included in the upload or not. The rows in question are:
>
>    - rows 279-281: Columns G and H are greyed out.
>    - rows 347-522 (the "Fike" citation rows): All columns are greyed out
>    except for A, B, D, and G.
>    - rows 1182-1229 and 1319-1366: These are greyed out in column A. Is
>    this significant?
>    - rows 1751-1770: These are greyed out in columns G and H.
>
> (Some of the grays are darker than others.)
>
> If the greyed-out rows represent rows that aren't ready for upload but
> that you may want to go back to later, the best procedure would to move
> these rows to a different data sheet. (You could call it "Switchgrass data
> part 2" or something like that.) Please only hand off to me as "ready to
> upload" data sheets where all the rows are to be uploaded. This way I don't
> have to manually remove rows before doing an upload, and I don't have to
> guess which rows really are supposed to be removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PecanProject/bety/issues/263#issuecomment-98773065>.
>



-- 
Emily Cheng
University of Illinois at Urbana-Champaign | 2015
Molecular and Cellular Biology Major | Chemistry Minor
Pre-Student Osteopathic Medicine Association | UIUC Chapter President
Illini Emergency Medical Services | Records Officer | EMT- B

**Comment by gsrohde** [comment]
@echeng7  I uploaded this after making a few changes, both in the database and in the CSV file.

Here are the changes I needed to make to the CSV file:

1. One Balasko citation year still said 1982 instead of 1984.
3. I had to change NCSU1 and NCSU2 to NCSU-1 and NCSU-2.
4. The row for the yield with id 2464 had "college" as the name of the cultivar.  Since there is no such cultivar name, I changed it to PMT279, which is the current value.  **If there really is a cultivar of Panicum virgatum named "college", we need to enter it in the database and update that yield record to use it.**

The upload inserts new rows.  But in this case, we want to use these new rows to supply the data to update already existing rows and then delete those new rows once we are done with them so that we don't have duplicate data.  I haven't done this yet.  **Before I do this, I need to know exactly which data columns need to be updated with new values and which ones should keep their old values.**  You mentioned that none of the dates need to be updated.  I assume that any column that's not contained in the data sheet should also stay the same.  Are there other columns that should stay the same?

**Comment by echeng7** [comment]
The changes you had made are correct, as well as only the date column being kept the same. 
@gsrohde

**Comment by gsrohde** [comment]
Old rows have been saved to `old_switchgrass_yields_rows.csv` in directory 
```
/home/n-z/srohde/BETYdb_database_maintenance/switchgrass_bulk_upload/
```
on ebi-forecast and then updated with the newly-uploaded versions.  The latter were then deleted.
