### ISSUE TITLE
Some of citations cannot be deleted

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#310]
Browser: Firefox 
Some of the listing Citations cannot be deleted by using the  delete action,  for example Data -> Citations -> delete the citation that "Author: Aasamaa Year: 2010"
An error message returned: PG::ForeignKeyViolation: ERROR: update or delete on table "citations" violates foreign key constraint "fk_yields_citations_1" on table "yields" DETAIL: Key (id)=(428) is still referenced from table "yields". : DELETE FROM "citations" WHERE "citations"."id" = $1

**Comment by dlebauer** [comment]
This is expected behavior, and is the result of the foreign key constraints that were added.

The interface does not allow records to be deleted if they will leave orphaned records (in this case, we require records on the yields table to have a citation). If you want to delete this citation, you would need to either change or delete all of the records it is linked to.

**Comment by robkooper** [comment]
We should make it clearer in the interface though, maybe list all those items that are there that need to be removed as well.
