### ISSUE TITLE
Link to CF guidelines in BETYdb resolves to local link - but should resolve to a full address

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#362]
Or, we should provide the web page in the BETYdb distribution.  For example, on our server it resolves to:https://modex.bnl.gov/guidelines.html but we don't have the html file.  Can we change this to resolve to https://www.betydb.org/guidelines.html? @dlebauer

**Comment by gsrohde** [comment]
It's in the Github repository (https://github.com/PecanProject/bety/blob/master/public/guidelines.html) so you should have it.  It should be in the /public directory under the Rails root folder.

**Comment by dlebauer** [comment]
@gsrohde and @robkooper this seems to be part of a bigger problem resolving
relative links in the ebi-forecast instance compared to other instances.
Another example is the /schemas page, which gives 404, e.g. here:
http://pecandev.igb.illinois.edu/bety/schemas

What is the easiest solution?

**Comment by gsrohde** [comment]
@dlebauer The problem with the schemas page has nothing to do with relative links ... the 404 just means I never bothered generated the schema documentation on Pecandev.  (I didn't think it necessary, but can do so if it would be useful.)

Most of the resolving-relative-links problems we have had in the past arose because links were hard-coded and didn't use the Rails-aware `link_to` function for generating link URLs or because the `link_to` function was used incorrectly—these links wouldn't resolve correctly when Bety was deployed to something like http://hostname/bety instead of just http://hostname.  Shawn's problem is a case of the `link_to` function being used incorrectly and I will fix it.

**Comment by gsrohde** [comment]
Update: This was fixed on the "Editing Variable" pages but not on the "New Variable" pages.

(@serbinsh Let me know if you find otherwise, that is, if the "CF Guidelines" on the "Editing Variable" page doesn't work in your copy of BETYdb.)

**Comment by dlebauer** [comment]
@serbinsh does this work now?

**Comment by gsrohde** [comment]
Fixed in release 4.5.
