### ISSUE TITLE
"Elevation" in sites show page should not be NaN

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#373]
I added a polygon to the sites in ebi-forecast.igb.illinois.edu/bety-mepp using

```sql
 UPDATE sites SET geometry = ST_Geomfromtext('POLYGON((40.062806716 -88.204463395 
  640.0,40.062776529 -88.206952545 640.0,40.063609417 -88.206951006 640.0,40.063617384  
  -88.205248163 640.0,40.063849512 -88.204853694 640.0,40.063896590 -88.204479037 
  640.0,40.062806716 -88.204463395 640.0))', 4326) WHERE ID=8000000002;
```

However, when I look at the show page for this record, the 'elevation' field is given as `NaN`. This is confusing since I specified the elevation.

**Comment by gsrohde** [comment]
@dlebauer The problem is that when dealing with non-Point geometries, the Rails sites pages (as we currently have them set up) first take the centroid of the geometry before extracting coordinates.  And ST_Centroid returns a two-dimensional point.

And this behavior probably makes sense: Consider the case where the geometry describes the perimeter of a hill.  If you based the displayed altitude on the altitude of the perimeter points, it would be much lower than the altitude of the center of the area.

Even in the case where the area is a flat but sloping surface so that the altitude of the center is in fact somewhere in between the altitudes of the perimeter points, it is not clear how the altitudes should be averaged.  Suppose we give them equal weight.  And suppose the lower perimeter of the area is much more ragged than the upper perimeter so that many more points are needed to describe it.  Then the average altitude we compute is likely to be significantly lower than the altitude of the center.

If the common use case for which you want to show the altitude of a region is for a flat field, then we could make a special case whereby _if_ the perimeter points all have the same altitude, then that will be taken as the representative altitude of the region; and otherwise the display for the altitude of a non-Point geometry could say "indeterminate" or something.  (By the way, I discussed this all with Max, and he suggested he could look in to the existence of libraries that might compute some sort of 3-D centroid, if it comes to that.  But again, doing so seems to me highly problematic for the afore-mentioned reasons.)

**This all brings up what is probably a much more serious issue:** If you go into the Edit Site page for some site that has a non-Point geometry, and if you hit "Edit" (even without editing anything) **the Rails app will silently replace your region with a point!** (a 3-D point corresponding to the centroid but with altitude set to zero, I think).  I'm about to make a separate issue for this.

[cc @max-zilla]

**Comment by dlebauer** [comment]
1. We need to disable the interface from deleting data
2. For now, hide elevation if it is non-point. But note that it is not nearly as important what the page shows as what people can query from the database (e.g. the lat, lon, elevation vector).

**Comment by gsrohde** [comment]
@dlebauer
* Re 1: I'll work on this (issue #374)
* Re 2: If you runs this
```sql
bety-mepp=# select st_astext(geometry) from sites where id % 10 = 2;
```
you get this:
```sql
                                                                                                               st_astext               
                                                                                                
---------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------
 POLYGON Z ((40.062806716 -88.204463395 640,40.062776529 -88.206952545 640,40.063609417 -88.206951006 640,40.063617384 -88.205248163 64
0,40.063849512 -88.204853694 640,40.06389659 -88.204479037 640,40.062806716 -88.204463395 640))
(1 row)
```
which is presumably what you put in, so there is no information loss until you apply the `ST_centroid` function.  If you want to abstract something from this in the form of a single 3-D Point, then you have to decide exactly how you want to do this and write (or find) the function that does what you want.  `ST_centroid` (together with coordinate functions) doesn't do what you want.

**Also**: By _hide_ elevation, do you just want nothing (blank) or some word like "indeterminate" or "not-applicable", or "unknown"?

**Comment by dlebauer** [comment]
talk with @max-zilla and Jong Lee to discuss implementing something like https://greatlakesmonitoring.org/geodashboard/#search using leaflet.js

consider making lat, lon, elevation read-only

create a separate issue for this implementation that describes going forward.

in the mean time stop this bug by making lat lon elevation read-only if non-point

**Comment by gsrohde** [comment]
@dlebauer I changed "NaN" to the empty string on the "Show" page.  See mockup at http://pecandev.igb.illinois.edu/sr/.

@max-zilla When you're inspired to work on a more comprehensive fix based on David's previous comment, let me know.
