### ISSUE TITLE
Editing a Site with a non-Point geometry will result in data-loss

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#374]
The geometry will silently be converted from a region to a point, even if you don't actually change anything before hitting "Update."

Need advice on what the behavior _should_ be.  Possibly: Don't allow updating non-Point geometries via the Rails app, and leave them alone when editing other attributes of a Site.

**Comment by dlebauer** [comment]
For now, it will be prudent to disable the interface so that this bug does not occur, i.e.

> Don't allow updating non-Point geometries via the Rails app

But a better solution would be to allow a user to copy/paste or upload either the two or three column dataset (lat, lon, elevation) that can be read by the script that @max-zilla wrote (#369, #373). (would this be an appropriate use of a clowder extractor?).

**Comment by gsrohde** [comment]
@dlebauer See proposed fix at http://pecandev.igb.illinois.edu/sr/.

**Comment by dlebauer** [comment]
@gsrohde comments in pull request #375

**Comment by gsrohde** [comment]
@dlebauer Release 4.5 fixes this bug but doesn't provide a way to enter non-point geometries.  I recommend closing this and if you want, make a new issue for a feature request.
