### ISSUE TITLE
Bulk Upload Not accepting File

### ISSUE THREAD

**Issue by abstewa2** [PecanProject/bety#384]
When I try to upload this file:
[phenotypes.txt](https://github.com/PecanProject/bety/files/138289/phenotypes.txt)

To the terra-test instance (http://pecandev.igb.illinois.edu/terra-test) of BETYdb, it doesn't recognize the variable names although they match the variables table. I get the following:

![image](https://cloud.githubusercontent.com/assets/17127438/13181345/502dd506-d6f2-11e5-9ff5-188236924e88.png)

**Comment by abstewa2** [comment]
It appears that the list of accepted traits is empty http://pecandev.igb.illinois.edu/terra-test/trait_covariate_associations

**Comment by gsrohde** [comment]
@abstewa2 Yes, that's the problem (the only problem, I hope).

The "canonical" list of `trait_covariate_associations`, the one we use on https://betydb.org is here: https://www.betydb.org/trait_covariate_associations  You should be able to see it without having administrative privileges if you log in as a guest and then go to the URL directly.

I was about to copy the table from the betydb.org database to the terra-test database but realized the foreign-key values have to be different because the variables tables aren't identical.

Unfortunately, we don't currently have a Web interface for modifying this table.  If you can let me know which columns in the CSV file correspond to the primary trait variable and which correspond to covariates, I can add the needed entries manually.

**Comment by dlebauer** [comment]
Only leafT is a covariate. Can we import the variables we need from
betydb.org?

**Comment by gsrohde** [comment]
@dlebauer leafT is the only needed variable that is not already in the terra-test database.

**Comment by gsrohde** [comment]
That said, we could wipe the terra-test `variables` table (and the two entries in the `traits` table, since they refer to it) and copy all or only the needed variables from betydb.org.  This would ensure that all column values on terra-test match the values for the corresponding variable on betydb.org.  If we use the same id column values as well, then we could just copy down the `trait_covariate_associations` table as is.

**Comment by dlebauer** [comment]
Yes, please wipe the traits and variables table and import the variables
that we need.

**Comment by abstewa2** [comment]
Thanks Scott!

**Comment by gsrohde** [comment]
Assuming this is fixed.  Closing.
