### ISSUE TITLE
RGeo gem not functioning correctly: setting geometry breaks /sites show page

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#423]
When I updated a site geometry:

```sql
UPDATE sites SET geometry = ST_Geomfromtext('POLYGON((-111.9747967 33.0764953 358.682,-111.9747966 33.0745228 358.675, -111.9750963 33.074485715 358.62,-111.9750964 33.0764584  358.638, -111.9747967 33.0764953 358.682))', 4326) WHERE ID=6000000001;
```

on bety6

the /sites page does not load https://terraref.ncsa.illinois.edu/bety/sites

If I run 

```sql
UPDATE sites SET geometry = NULL WHERE ID=6000000001;
```

It will load again

**Comment by gsrohde** [comment]
This seems to be an issue others have discovered: https://github.com/rgeo/activerecord-postgis-adapter/issues/173

This is one of the hazards of not standardizing on specific versions of, for example, PostgreSQL and PostGIS and supporting libraries.

If this problem is holding you up, I could hack the bety6 code to do something like only calling `centroid` on point geometries until I have a chance to dig into this problem further.

Let me know.

**Comment by gsrohde** [comment]
Actually, the geos version issue may be a red hering: it seems like geos isn't even installed on bety6.  Ask @robkooper if he installed it.  Looks like I should add a test for display of non-point sites.
