### ISSUE TITLE
In API, 'associated <tablename> ids' should be optional (off by default)

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#432]
The API response can get very large if the ids of all associated records are returned. 

For example, if I just want a list of all of the records in the variables table, each record states all associated trait records. When there are many thousand, it gets unweildy. 

https://terraref.ncsa.illinois.edu/bety-test/api/beta/variables?limit=1&key=9999999999999999999999999999999999999999

It seems just as easy to query the variables table for an id and then send another query to list the associated records.

**Comment by gsrohde** [comment]
Now, only a count of associated rows is returned, to a listing of all of the ids.

**Comment by dlebauer** [comment]
@gsrohde I revised the title to reflect that it should be kept as an option rather than removed completely. 

But rather than prescribing how it is implemented, I'll give an example use case that we will need to support:

1. Find all sites where name partially matches, e.g. "Season 2"
2. Find all traits associated with sites from 1)
3. Find all treatments associated with results from 2)
4. Find all managements associated with treatments from 3)

**Comment by gsrohde** [comment]
To-do: Now that showing associated ids is off by default, I have to add the option to show them.

**Comment by gsrohde** [comment]
@dlebauer I added a parameter "associations_mode" with possible values "count", "ids", and "full_info" to control the amount of information to show about associations.  If you omit the parameter, the API behaves as it did before, showing association counts when a list of objects (e.g. "sites") is requested and showing full information about associations when a particular object is requested.

For the scenario you outlined, this makes it possible to get the information you want, but it takes several queries. The sequence of HTTP requests would be roughly as follows (I'm leaving out the hostname and API key parameter here):

1. `/api/beta/sites?sitename=~Season+2&associations_mode=ids` will return a list of Season 2 sites along with id numbers of all traits associated with each.
2. For each trait id returned in 1, the information returned by a request to `/api/beta/traits/<trait id>` will include information about the treatment associated with the trait, including its id.
3. For the treatment returned in 2, `/api/beta/treatments/<treatment id>` will return a list of managements associated with that treatment (along with other information).

If you use "full_info" mode in step one, you will get more information about each trait.  This information will include the `treatment_id`, so step 2 could be eliminated.  If there are a huge number of traits associated with Season 2 sites, however, there may be some risk the server will time out before processing the request.

It would be possible to program things so that you could get all of this information from one HTTP request, but it would take more thought to figure out how really only to get the data you are interested in and avoid the timeout issues we were having before.

This change has been committed to master, so if you have a working BETYdb copy, you can try it out.  Note, though, that even without this change you could get the information outlined in your scenario, but it would take a different sequence of HTTP requests:

1. `/api/beta/sites?sitename=~Season+2` will give a list of Season 2 sites.
2. For any site id returned from the query in 1, `/api/beta/sites/<site id>` will give a list of traits associated with that site with the `treatment_id` shown for each.  Then proceed with step 3 above.

**Comment by gsrohde** [comment]
Fixed by release 4.15.
