### ISSUE TITLE
Need "unique_run_variable_input_combination" constraint to be removed

### ISSUE THREAD

**Issue by istfer** [PecanProject/bety#462]
I am working on a new implementation of the emulator method in PEcAn. For a given run, I compare  model outputs and data, and then calculate the sufficient statistics (SS) more than once for each proposed bias parameter. 

I want to store these (multiple) SS values (per unique run_id, variable_id and input_id) in the `likelihood` table but the `unique_run_variable_input_combination` constraint doesn't let me.

Is it possible to remove or relax this constraint for the likelihood table?

**Comment by gsrohde** [comment]
@dlebauer Would you take a look at this request?  Were we rash in imposing this constraint, or is there a better alternative to the way she wishes to use this table?  I don't think I have enough domain knowledge to evaluate whether or not this is a reasonable request.

**Comment by dlebauer** [comment]
@gsrohde we implemented these before they were used very much, and supporting an actual use case is a reasonable request. I'll punt to @robkooper and @mdietze

**Comment by mdietze** [comment]
This is a reasonable request. Istem's the one who's been deep in the weeds on this part of pecan and I've discussed this with her -- relaxing this constraint is the best solution to the problem of needing to estimate non-model parameters during data assimilation. Specifically, for a given run/data/variable combination we need to evaluate multiple possible non-model parameters ( bias, variance etc). We want to store these evaluations in the DB since this is key to our plan for distributed data assimilation

**Comment by robkooper** [comment]
I'd say for now drop the constraint.

**Comment by gsrohde** [comment]
Fixed by release 4.14.
