### ISSUE TITLE
Add cultivars_sites table

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#475]
Scott ... please define this issue

https://github.com/terraref/computing-pipeline/issues/201#issuecomment-267458905

**Comment by gsrohde** [comment]
This will be a simple join table with columns for `cultivar_id`, `site_id`, and the usual administrative columns (timestamps and `id`).  Foreign-key constraints (and not-null constraints) will be added so that rows in this table must refer to existing sites and cultivars, and cultivar or site rows can't be removed if they are referenced by a row in this table.  Additionally, the `site_id` must be unique: a site may be associated with at most one cultivar (via this table).

Additionally, there will be some sort of constraints or trigger functions that ensure consistency between traits, sites, and cultivars.  Specifically:

1. Whenever a trait is added, if it refers to a site that is associated with a cultivar, then the `cultivar_id` for that trait defaults to that cultivar.  [This requires a trigger function.]
1. If an update to a trait with null `cultivar_id` changes its `site_id` to a site with an associated cultivar, the `cultivar_id` is automatically updated to refer to that cultivar.  [This requires a trigger function.]
1. If an update to a trait with a _non-null_ `cultivar_id` changes its `site_id` to a site with an associated cultivar, the `cultivar_id` must match that cultivar; otherwise an error is returned.  (In other words, to change the `cultivar_id` in this case, one must either (a) first update the trait to set its `cultivar_id` to null and then do a second update to change the `site_id`, letting the `cultivar_id` be set automatically, or (b) explicitly set the `cultivar_id` to the correct cultivar in the same update statement that updates the `site_id`.)  [This is essentially a constraint but probably must be implemented by a trigger function.]
1. If `cultivar_id` is explicitly specified in a trait insert or update statement, it must match the cultivar associated with the trait's site (if any).  [This is essentially a constraint but probably must be implemented by a trigger function.]
1. If the cultivar associated with a site is updated, the `cultivar_id`s of all traits associated with that site will be updated as well.  [This requires a trigger function.]
1. If a cultivar becomes associated with a site that does not yet have an associated cultivar, the `cultivar_id`s for all traits associated with that site must either be null or must already point to the correct cultivar; in this case the nulls will all be automatically replaced by the id of the correct cultivar.  But if any existing trait points to some different cultivar, the insert statement to add the new site-cultivar association will fail.

These rules are formulated with the goal of achieving the right balance between convenience and preventing data loss.

The database invariant that we are trying to maintain can be expressed as follows:
```text
(for all cultivars_sites cs) (for all traits t)[if cs.site_id = t.site_id, then t.cultivar_id = cs.cultivar_id]
```

Questions: (a) If the site for a trait is changed from a site having an associated cultivar to one that does not have an associated cultivar, should anything automatic happen to the `cultivar_id`?  Or should a warning be issued? (b) If a cultivar is disassociated from a site, should anything happen to the `cultivar_id`s of traits associated with that site?

Ditto all of the above constraints/triggers for yields.  (Or alternatively, don't allow yields to refer to a site connected with a cultivar.)

**Comment by dlebauer** [comment]
@gsrohde any updates on this?

**Comment by gsrohde** [comment]
Still working on it.

**Comment by gsrohde** [comment]
See pull request #504 and attached document.

**Comment by dlebauer** [comment]
@gsrohde 

### Answers to ? in https://github.com/PecanProject/bety/issues/475#issuecomment-272308593

> (a) If the site for a trait is changed from a site having an associated cultivar to one that does not have an associated cultivar, should anything automatic happen to the cultivar_id? 

We rarely change sites. If someone changes a site from a site that has a cultivar to another site with a cultivar, then the cultivar should also change. Otherwise, a warning should be given. The warning should be rare enough that it could be handled by an administrator.

> (b) If a cultivar is disassociated from a site, should anything happen to the cultivar_ids of traits associated with that site?

the cultivars should also be dissociated.

### Comments on document in #504 

When I originally wrote this specification I understood that the plots boundaries would change every season. Now, it seems that the plots are the same each season but have different cultivars.

I will use what you have and duplicate the existing plots to new seasons. This feature should be deployed asap. 

However, the reality is that each site may have a unique cultivar each season. I'd also like your assessment of how difficult it would be to update the functionality so that the requirement is that each [site_id, experiment_id] has a unique cultivar_id (rather than each site_id).

**Comment by gsrohde** [comment]
@dlebauer Since you went ahead and pulled request #504 after making these comments, I wasn't sure if you just want me to deploy what I have now and worry about addressing the concerns you raise in your comments later.

Regarding your comments on https://github.com/PecanProject/bety/issues/475#issue-200448453, I would tend to favor handling these things in Rails rather than at the database level.  If a user is trying to make a change that is questionable, a warning can be issued with information about how to go ahead and make the change.

Regarding re-using sites with different cultivars, it seems to me that we discussed this before and decided against it.  In any case, it's not clear to me what in the database associates a given trait with a given experiment, though I imagine it might work like this: Find the experiments associated with the given trait's site.  Choose the experiment whose date range includes the date of the trait.  (But will there necessarily always only be one, or can multiple experiments be carried out on the same site simultaneously?)  If we go this route, it might make sense to junk the `sites_cultivars` table and just add a `cultivar_id` column to the join table `experiments_sites`.

Alternatively, a date range could be included in the `sites_cultivars` table and the requirement that `site_id` values in this table be unique could be replaced by the requirement that rows sharing the same `site_id` value can't have overlapping date ranges.

**Comment by dlebauer** [comment]
>  I wasn't sure if you just want me to deploy what I have now 

Yes, per https://github.com/PecanProject/bety/pull/504#pullrequestreview-36626653 "please deploy ASAP"

> Regarding re-using sites with different cultivars

Please disregard this comment. We will no longer plan to re-use the sites with different cultivars. 

> If we go this route, it might make sense to junk the sites_cultivars table and just add a cultivar_id column to the join table experiments_sites.

That is actually more appealing. However, I am concerned about further delaying this feature release. How long would this take to implement?

**Comment by gsrohde** [comment]
I think I could deploy it to bety6 right now and then worry about doing an official release.  There might be a problem if people are syncing with bety6 though.

**Comment by dlebauer** [comment]
Would be great to have this on bety6 and bety8 terra-mepp. But we also need the experiments API endpoint. How long would it take for a release?

**Comment by gsrohde** [comment]
The experiments API would be part of what I deploy as well.  The main extra time of doing a release is writing up some notes.  I’ll start writing up notes now though.  But if you say, I’ll deploy to bety6 and bety8 before I’m done.

**Comment by gsrohde** [comment]
OK, I did a release (with the experiments API endpoint also) and deployed to ebi-forecast, bety6, and terra-mepp.   I hope I got it right.

—Scott

**Comment by gsrohde** [comment]
@dlebauer Close?
