### ISSUE TITLE
Errors in search --> download, output csv 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#482]
High priority

* Entity and Methods columns only return values in the first record
* Citation information should match that in the home page / footer 
* return raw date

**Comment by gsrohde** [comment]
@dlebauer If the the entity and methods columns only returned values in the first record, then that was probably the only returned record for which they were not blank.  If you think otherwise, please provide and example that demonstrates this.

Note that the "raw date" will most likely show up in Excel without timezone offset information and with the time interpreted as Central time.  You may have to view the CSV file as a text file to properly interpret the raw date.  Of course, the date and time columns together provide the proper interpretation, and these most likely will show up correctly in Excel.

By "High priority", do you mean you would like this changed and deployed by Friday?

**Comment by dlebauer** [comment]
I'll close this -

**Comment by gsrohde** [comment]
@dlebauer Does this mean you don't want 2 and 3 implemented?  I would think you'd at least want 2 (citation information).

**Comment by dlebauer** [comment]
Sorry I didn't read the original post again and missed this. Yes to 2&3

**Comment by gsrohde** [comment]
Fixed by release 4.15.
