### ISSUE TITLE
Enable customization of google analytics tracking code

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#511]
add the ability to set the google analytics tracking code to [config/application.yml](https://github.com/PecanProject/bety/blob/master/config/application.yml)

@gsrohde where is the code currently stored? I can't seem to find it grepping through the repository, but it does seem to be working.

**Comment by gsrohde** [comment]
@dlebauer I think what you are looking for is lines 74–84 of `app/views/layouts/application.html.erb` and perhaps 28–39 of `app/views/layouts/fullscreen.html.erb`.  (The latter hasn't been revised since July 2012 and I'm not sure if it is actually used.  I think it's for iPhones, but since I don't have one, it's not easy for me to test this.)
