### ISSUE TITLE
Mismatched cultivar_id / species_id in traits_and_yields_view

### ISSUE THREAD

**Issue by infotroph** [PecanProject/bety#565]
[Task LIst, added 3-14-2018:]

* [ ] Clean up EBI data (https://www.betydb.org)
* [ ] Clean up TERRA-MEPP data (https://terra-mepp.illinois.edu/bety) 

[TERRA-REF data is OK]

---

```
select distinct cultivar_id, cultivar, scientificname, species_id from traits_and_yields_view  where cultivar_id=10;
 cultivar_id |   cultivar   |  scientificname  | species_id 
-------------+--------------+------------------+------------
          10 | Cave-In-Rock | Acer rubrum      |         30
          10 | Cave-In-Rock | Panicum virgatum |        938
(2 rows)
```

Looks like the weird one is id 49920:
```
select distinct id,cultivar_id, cultivar, scientificname, species_id from traits_and_yields_view  where cultivar_id=10 and species_id!=938;
  id   | cultivar_id |   cultivar   | scientificname | species_id 
-------+-------------+--------------+----------------+------------
 49920 |          10 | Cave-In-Rock | Acer rubrum    |         30
```

**Comment by infotroph** [comment]
Here's a reasonable-looking but poorly tested query to find the other mismatched records:

```
SELECT 	cultivar_id, 
		COUNT(distinct species_id),
		specie_id AS correct_species_id,
		species.scientificname AS correct_scientificname
	INTO tmp 
	FROM traits_and_yields_view
		JOIN cultivars ON cultivars.id = traits_and_yields_view.cultivar_id
		JOIN species ON cultivars.specie_id = species.id
	GROUP BY cultivar_id, specie_id, species.scientificname;

DELETE FROM tmp WHERE count <= 1;

SELECT DISTINCT 
		id,
		cultivar_id,
		correct_species_id,
		correct_scientificname,
		species_id,
		scientificname 
	FROM traits_and_yields_view
		NATURAL JOIN tmp 
	WHERE species_id != correct_species_id;
```

On my machine, this identified 610 records. The first 10:

```
  id  | cultivar_id | correct_species_id | correct_scientificname | species_id |         scientificname          
------+-------------+--------------------+------------------------+------------+---------------------------------
 1361 |          68 |               1478 | Miscanthus sinensis    |      51217 | Salix schwerinii × S. viminalis
 1362 |          69 |               1478 | Miscanthus sinensis    |      51217 | Salix schwerinii × S. viminalis
 1363 |          70 |               1478 | Miscanthus sinensis    |      51217 | Salix schwerinii × S. viminalis
 7587 |         398 |              33738 | Saccharum officinarum  |         29 | Acer pseudoplatanus
 7588 |         398 |              33738 | Saccharum officinarum  |         29 | Acer pseudoplatanus
 7589 |         398 |              33738 | Saccharum officinarum  |         29 | Acer pseudoplatanus
 7598 |         398 |              33738 | Saccharum officinarum  |       2583 | Salix viminalis
 7599 |         398 |              33738 | Saccharum officinarum  |       2583 | Salix viminalis
 7600 |         398 |              33738 | Saccharum officinarum  |       2583 | Salix viminalis
 7601 |         398 |              33738 | Saccharum officinarum  |       2583 | Salix viminalis
```

**Comment by infotroph** [comment]
The above query also won't find cultivars where all records have the *same* wrong species.

**Comment by dlebauer** [comment]
@gsrohde did you ever implement a constraint that required [id, specie_id] in the cultivars table to match the [cultivar_id, specie_id] in the traits table?

**Comment by gsrohde** [comment]
I don't recall if I ever drafted a constraint for this, though I noted the need for one here: https://www.overleaf.com/2086241dwjyrd#/5297403/ (section 3.26 notes the need for this constraint in the traits table, and section 3.31 notes it for the yields table).  Also, there is a Redmine issue noting the problem here: https://ebi-forecast.igb.illinois.edu/redmine/issues/2389, and Github issues #248 and #253 mention the need for species-cultivar consistency in the trait and yields tables (respectively) among the many other constraints to be implemented.

If I did ever draft a constraint, it's likely that the task of cleaning up existing data stood in the way of implementing it.

**Comment by gsrohde** [comment]
@dlebauer I remember now.  There is a constraint to this effect (a trigger function, actually).  I implemented it when I added constraints to associate cultivars with sites.  But existing bad data is "grandfathered in".

You can see the constraint in effect if you try to do the following update:

```sql
update traits set specie_id = 30 where id = 49920;
```

(The `specie_id` in this row already _is_ 30, but nevertheless, this returns an error, even though nothing would actually change (except maybe `updated_at`) if the update succeeded.)

Updating to the proper value should succeed:

```sql
update traits set specie_id = 938 where id = 49920;
```

So the issue is a matter of cleaning up existing data.

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #3](https://github.com/PecanProject/bety-data/issues/3) via [**ZenHub**](https://www.zenhub.com/)
