### ISSUE TITLE
"Site has no assigned time zone in these rows:" error in Bulk Upload

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#602]
<img width="797" alt="screen shot 2018-10-11 at 9 28 01 am" src="https://user-images.githubusercontent.com/3067369/46809464-84876e00-cd3c-11e8-8311-ec29b7a57360.png">

How do I deal with this error? I cannot figure out how to set a TZ and I suspect it is supposed to do this automatically given the lat/long or country /state?  But in my case I am using a site in Panama

**Comment by serbinsh** [comment]
Looks like site table does have time_zone

```
bety=> select * from sites where false;
 id | city | state | country | mat | map | soil | som | notes | soilnotes | created_at | updated_at | sitename | greenhouse | user_id | sand_pct | cl
ay_pct | geometry | time_zone
----+------+-------+---------+-----+-----+------+-----+-------+-----------+------------+------------+----------+------------+---------+----------+---
-------+----------+-----------
(0 rows)
```

BUT my version of the web interface (which is pretty recent) doesnt have that as an input option?

**Comment by serbinsh** [comment]
Fixed my upload issue by doing this:

```
bety=> UPDATE sites SET time_zone = 'EST' WHERE sites.id = 2000000017;
UPDATE 1
bety=> select time_zone from sites where sites.id = 2000000017;
 time_zone
-----------
 EST
(1 row)
```

so maybe we should add a "Time Zone" field to the web interface?

**Comment by serbinsh** [comment]
BUT i then run into this error where I am trying to set "Method"

<img width="1040" alt="screen shot 2018-10-11 at 10 37 30 am" src="https://user-images.githubusercontent.com/3067369/46811927-b5b66d00-cd41-11e8-88ac-459b4fe1e3dd.png">

**Comment by gsrohde** [comment]
[copied from Slack:]

The value for time_zone should always be a daylight/standard time-agnostic name such as "America/Phoenix", and it should be the name of a zone that follows the daylight savings time rules for the site location.  A list of these names can be found by doing the query "SELECT * from pg_timezone_names;" and looking at the "name" column.  (You could also query the "sites" table to see what names are already being used.)  An important thing to note about this table (a view, actually) is that the last three columns of it will change according to the time of year.  For example, the entry "America/Chicago | CDT | -05:00:00 | t" will change to "America/Chicago | CST | -06:00:00 | f" once Chicago switches back to standard time.  Note that, for example, a site in Phoenix should use "America/Phoenix" rather than "US/Mountain" because the former will use standard time year-round whereas the latter doesn't.  And in case I didn't make it clear, the database stores the date/time in UTC; it computes the value to use from the time zone and the local date and time.
