### ISSUE TITLE
Customize web pages for UA installation

### ISSUE THREAD

**Issue by Chris-Schnaufer** [PecanProject/bety#624]
From @dlebauer 
> Also customize web home pages
> 
>   create site-specific application.yml for BETYdb
>   create local config.php for PEcAn from config.example.php

**Comment by Chris-Schnaufer** [comment]
Refer to #616 for additional information

**Comment by dlebauer** [comment]
for config.example.php
* google maps API key is shared w/ Chris in stache.arizona.edu
* I will leave the rest of the configuration to @KristinaRiemer with help from you and the PEcAn community
   * I would be curious if the simple bety interfaces still work (what happens if we uncomment the line `simpleBety = True`?

for application.yml and defaults.yml
- see https://github.com/PecanProject/bety/pull/447 for configuration instructions
- can use my email and phone number for contact information

**Comment by dlebauer** [comment]
moved to https://github.com/danforthcenter/sentinel-detection/issues/19
