### ISSUE TITLE
Betydb dates for TerraRef field measurements

### ISSUE THREAD

**Issue by NewcombMaria** [PecanProject/bety#670]
@kimberlyh66 @dlebauer manual measurement data downloaded from Betydb during the TERRA-REF hackathons look like the dates associated with the S4 field measurements are one day earlier in the downloaded data compared to the uploaded data, possibly for other seasons of field measurements as well.

**Comment by gsrohde** [comment]
@NewcombMaria Were these API uploads or Bulk Upload wizard uploads?  Keep in mind that the raw date as stored in the traits table of the database may not be the same as the date on site.  The former is always (or always should be) the date UTC time.  If a date without time-of-day is entered, the stored value should be the UTC equivalent of midnight site time.  Also, how are you downloading data?

**Comment by NewcombMaria** [comment]
@gsrohde the few data sets that were downloaded during the hackathon had been uploaded using the Bulk Upload wizard, as date without time-of-day.  Not sure about the download steps.

**Comment by gsrohde** [comment]
@NewcombMaria I see a bunch of data from July 2018 uploaded last week.  Is this what you are referring to?

**Comment by NewcombMaria** [comment]
@gsrohde the data we looked at recently at the hackathon actually go back to 2017, field data collected in summer 2017 and uploaded I think in late fall 2017.

**Comment by gsrohde** [comment]
@NewcombMaria Here is what I think is going on with this data:

Prior to BETYdb release 4.21 (released June 18 of last year), the bulk upload wizard did not accept time-of-day in the date field.  Moreover, it represented a date-without-time as being midnight on the date specified _machine time_.  Since the machine running BETYdb for TERRA-REF is located in Urbana, this is midnight _Central_ time.  The timestamp is converted to UTC time when it is stored in the database.  So, for example, if the CSV file gave the date as `2017-05-17`, this would have been stored in the database as `2017-05-17 05:00:00` because it is 5 a.m. UTC time when it is midnight in Urbana (in summer months).  But now that dates for trait measurements are converted to local (site) time when displayed in the Advanced Search results (or using the search API endpoint), the date will be displayed as "2017 May 16 (America/Phoenix)". (The time will appear as "[time unspecified or unknown]" since the dateloc is 5.)  This is because `2017-05-17 05:00:00` UTC converts to `2017-05-16 22:00:00` Maricopa time.

Since the 4.21 release, dates-without-time for sites in Arizona will be stored correctly as the UTC equivalent of midnight Arizona time.  So, for the above example, the date would go into the database as `2017-05-17 07:00:00`.

It's probably a fairly safe bet that dates for Arizona trait measurements taken in summer with a time portion of `05:00:00` should all be incremented by two hours.  (Similarly, those in winter with a time portion of `06:00:00` should be incremented by one hour.)

**Comment by NewcombMaria** [comment]
Thanks @gsrohde for the helpful info.  @dlebauer and @kimberlyh66 from Scott's explanation, is it possible for you to make the date correction/conversion in Betydb for the data uploaded by the bulk wizard before the 4.21 release?

**Comment by dlebauer** [comment]
it looks like all of these can be corrected by shifting the time zone from UTC to America/Pheonix

This applies to all data w/ Newcomb as citation and uploaded before June 18 2018 where the time is 05:00:00 UTC (i.e. no time stamp). Season 4 data for sure, perhaps also seasons 1 and 2.

**Comment by dlebauer** [comment]
replaced by https://github.com/terraref/reference-data/issues/274
